### PR TITLE
Move the page-accessibility-check library into accessibility-assessment repository

### PR DESCRIPTION
**Pull request by kyle-bowden**
[We have spoken to B&D](https://hmrcdigital.slack.com/archives/G0JJ0ADLY/p1651576122658859) in regards to the Jenkins issues we were having around building a jar in the docker image.

Unfortunately, B&D does not support a Jenkins agent with enough memory to do what we need, as a fix for this, we will be creating the jar locally when a "sbt clean test" is run. The jar file will be pushed as part of a commit. This will remove the need to build the jar in the Jenkins image but also give us the ability to generate the jar file for integration testing.

### CODE REVIEW

**Comment by ejayaraman** [comment]
Retest this please!

**Comment by ejayaraman** [comment]
Retest this please!

**Comment by ejayaraman** [comment]
Retest this please!

**Comment by ejayaraman** [comment]
Retest this please!

**Review by tmc-ee — APPROVED** [review]

**Pull request merged**
